// Code generated by MockGen. DO NOT EDIT.
// Source: wallet/manager/interface.go
//
// Generated by this command:
//
//	mockgen -source=wallet/manager/interface.go -destination=wallet/manager/manager_mock.go -package=manager
//

// Package manager is a generated GoMock package.
package manager

import (
	reflect "reflect"

	crypto "github.com/pactus-project/pactus/crypto"
	amount "github.com/pactus-project/pactus/types/amount"
	tx "github.com/pactus-project/pactus/types/tx"
	wallet "github.com/pactus-project/pactus/wallet"
	types "github.com/pactus-project/pactus/wallet/types"
	gomock "go.uber.org/mock/gomock"
)

// MockIManager is a mock of IManager interface.
type MockIManager struct {
	ctrl     *gomock.Controller
	recorder *MockIManagerMockRecorder
	isgomock struct{}
}

// MockIManagerMockRecorder is the mock recorder for MockIManager.
type MockIManagerMockRecorder struct {
	mock *MockIManager
}

// NewMockIManager creates a new mock instance.
func NewMockIManager(ctrl *gomock.Controller) *MockIManager {
	mock := &MockIManager{ctrl: ctrl}
	mock.recorder = &MockIManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIManager) EXPECT() *MockIManagerMockRecorder {
	return m.recorder
}

// AddressInfo mocks base method.
func (m *MockIManager) AddressInfo(walletName, address string) (*types.AddressInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressInfo", walletName, address)
	ret0, _ := ret[0].(*types.AddressInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddressInfo indicates an expected call of AddressInfo.
func (mr *MockIManagerMockRecorder) AddressInfo(walletName, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressInfo", reflect.TypeOf((*MockIManager)(nil).AddressInfo), walletName, address)
}

// AddressLabel mocks base method.
func (m *MockIManager) AddressLabel(walletName, addr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressLabel", walletName, addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddressLabel indicates an expected call of AddressLabel.
func (mr *MockIManagerMockRecorder) AddressLabel(walletName, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressLabel", reflect.TypeOf((*MockIManager)(nil).AddressLabel), walletName, addr)
}

// Balance mocks base method.
func (m *MockIManager) Balance(walletName, addr string) (amount.Amount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Balance", walletName, addr)
	ret0, _ := ret[0].(amount.Amount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Balance indicates an expected call of Balance.
func (mr *MockIManagerMockRecorder) Balance(walletName, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Balance", reflect.TypeOf((*MockIManager)(nil).Balance), walletName, addr)
}

// BroadcastTransaction mocks base method.
func (m *MockIManager) BroadcastTransaction(walletName string, trx *tx.Tx) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BroadcastTransaction", walletName, trx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BroadcastTransaction indicates an expected call of BroadcastTransaction.
func (mr *MockIManagerMockRecorder) BroadcastTransaction(walletName, trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadcastTransaction", reflect.TypeOf((*MockIManager)(nil).BroadcastTransaction), walletName, trx)
}

// CreateWallet mocks base method.
func (m *MockIManager) CreateWallet(walletName, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateWallet", walletName, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateWallet indicates an expected call of CreateWallet.
func (mr *MockIManagerMockRecorder) CreateWallet(walletName, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateWallet", reflect.TypeOf((*MockIManager)(nil).CreateWallet), walletName, password)
}

// GetValidatorAddress mocks base method.
func (m *MockIManager) GetValidatorAddress(publicKey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValidatorAddress", publicKey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetValidatorAddress indicates an expected call of GetValidatorAddress.
func (mr *MockIManagerMockRecorder) GetValidatorAddress(publicKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValidatorAddress", reflect.TypeOf((*MockIManager)(nil).GetValidatorAddress), publicKey)
}

// ListAddresses mocks base method.
func (m *MockIManager) ListAddresses(walletName string, opts ...wallet.ListAddressOption) ([]types.AddressInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListAddresses", varargs...)
	ret0, _ := ret[0].([]types.AddressInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAddresses indicates an expected call of ListAddresses.
func (mr *MockIManagerMockRecorder) ListAddresses(walletName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAddresses", reflect.TypeOf((*MockIManager)(nil).ListAddresses), varargs...)
}

// ListTransaction mocks base method.
func (m *MockIManager) ListTransaction(walletName string, opts ...wallet.ListTransactionsOption) ([]*types.TransactionInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListTransaction", varargs...)
	ret0, _ := ret[0].([]*types.TransactionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransaction indicates an expected call of ListTransaction.
func (mr *MockIManagerMockRecorder) ListTransaction(walletName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransaction", reflect.TypeOf((*MockIManager)(nil).ListTransaction), varargs...)
}

// ListWallets mocks base method.
func (m *MockIManager) ListWallets() ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListWallets")
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListWallets indicates an expected call of ListWallets.
func (mr *MockIManagerMockRecorder) ListWallets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListWallets", reflect.TypeOf((*MockIManager)(nil).ListWallets))
}

// LoadWallet mocks base method.
func (m *MockIManager) LoadWallet(walletName string, opts ...wallet.OpenWalletOption) error {
	m.ctrl.T.Helper()
	varargs := []any{walletName}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "LoadWallet", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// LoadWallet indicates an expected call of LoadWallet.
func (mr *MockIManagerMockRecorder) LoadWallet(walletName any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadWallet", reflect.TypeOf((*MockIManager)(nil).LoadWallet), varargs...)
}

// MakeBondTx mocks base method.
func (m *MockIManager) MakeBondTx(walletName, sender, receiver, publicKey string, amt amount.Amount, opts ...wallet.TxOption) (*tx.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName, sender, receiver, publicKey, amt}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeBondTx", varargs...)
	ret0, _ := ret[0].(*tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeBondTx indicates an expected call of MakeBondTx.
func (mr *MockIManagerMockRecorder) MakeBondTx(walletName, sender, receiver, publicKey, amt any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName, sender, receiver, publicKey, amt}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeBondTx", reflect.TypeOf((*MockIManager)(nil).MakeBondTx), varargs...)
}

// MakeTransferTx mocks base method.
func (m *MockIManager) MakeTransferTx(walletName, sender, receiver string, amt amount.Amount, opts ...wallet.TxOption) (*tx.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName, sender, receiver, amt}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeTransferTx", varargs...)
	ret0, _ := ret[0].(*tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeTransferTx indicates an expected call of MakeTransferTx.
func (mr *MockIManagerMockRecorder) MakeTransferTx(walletName, sender, receiver, amt any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName, sender, receiver, amt}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeTransferTx", reflect.TypeOf((*MockIManager)(nil).MakeTransferTx), varargs...)
}

// MakeUnbondTx mocks base method.
func (m *MockIManager) MakeUnbondTx(walletName, validator string, opts ...wallet.TxOption) (*tx.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName, validator}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeUnbondTx", varargs...)
	ret0, _ := ret[0].(*tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeUnbondTx indicates an expected call of MakeUnbondTx.
func (mr *MockIManagerMockRecorder) MakeUnbondTx(walletName, validator any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName, validator}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeUnbondTx", reflect.TypeOf((*MockIManager)(nil).MakeUnbondTx), varargs...)
}

// MakeWithdrawTx mocks base method.
func (m *MockIManager) MakeWithdrawTx(walletName, sender, receiver string, amt amount.Amount, opts ...wallet.TxOption) (*tx.Tx, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName, sender, receiver, amt}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "MakeWithdrawTx", varargs...)
	ret0, _ := ret[0].(*tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MakeWithdrawTx indicates an expected call of MakeWithdrawTx.
func (mr *MockIManagerMockRecorder) MakeWithdrawTx(walletName, sender, receiver, amt any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName, sender, receiver, amt}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MakeWithdrawTx", reflect.TypeOf((*MockIManager)(nil).MakeWithdrawTx), varargs...)
}

// Mnemonic mocks base method.
func (m *MockIManager) Mnemonic(walletName, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mnemonic", walletName, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Mnemonic indicates an expected call of Mnemonic.
func (mr *MockIManagerMockRecorder) Mnemonic(walletName, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mnemonic", reflect.TypeOf((*MockIManager)(nil).Mnemonic), walletName, password)
}

// NewAddress mocks base method.
func (m *MockIManager) NewAddress(walletName string, addressType crypto.AddressType, label string, opts ...wallet.NewAddressOption) (*types.AddressInfo, error) {
	m.ctrl.T.Helper()
	varargs := []any{walletName, addressType, label}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "NewAddress", varargs...)
	ret0, _ := ret[0].(*types.AddressInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewAddress indicates an expected call of NewAddress.
func (mr *MockIManagerMockRecorder) NewAddress(walletName, addressType, label any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{walletName, addressType, label}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewAddress", reflect.TypeOf((*MockIManager)(nil).NewAddress), varargs...)
}

// PrivateKey mocks base method.
func (m *MockIManager) PrivateKey(walletName, password, addr string) (crypto.PrivateKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrivateKey", walletName, password, addr)
	ret0, _ := ret[0].(crypto.PrivateKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrivateKey indicates an expected call of PrivateKey.
func (mr *MockIManagerMockRecorder) PrivateKey(walletName, password, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrivateKey", reflect.TypeOf((*MockIManager)(nil).PrivateKey), walletName, password, addr)
}

// RestoreWallet mocks base method.
func (m *MockIManager) RestoreWallet(walletName, mnemonic, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreWallet", walletName, mnemonic, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreWallet indicates an expected call of RestoreWallet.
func (mr *MockIManagerMockRecorder) RestoreWallet(walletName, mnemonic, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreWallet", reflect.TypeOf((*MockIManager)(nil).RestoreWallet), walletName, mnemonic, password)
}

// SetAddressLabel mocks base method.
func (m *MockIManager) SetAddressLabel(walletName, addr, label string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAddressLabel", walletName, addr, label)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAddressLabel indicates an expected call of SetAddressLabel.
func (mr *MockIManagerMockRecorder) SetAddressLabel(walletName, addr, label any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAddressLabel", reflect.TypeOf((*MockIManager)(nil).SetAddressLabel), walletName, addr, label)
}

// SetDefaultFee mocks base method.
func (m *MockIManager) SetDefaultFee(walletName string, fee amount.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultFee", walletName, fee)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultFee indicates an expected call of SetDefaultFee.
func (mr *MockIManagerMockRecorder) SetDefaultFee(walletName, fee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultFee", reflect.TypeOf((*MockIManager)(nil).SetDefaultFee), walletName, fee)
}

// SignMessage mocks base method.
func (m *MockIManager) SignMessage(walletName, password, addr, msg string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignMessage", walletName, password, addr, msg)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SignMessage indicates an expected call of SignMessage.
func (mr *MockIManagerMockRecorder) SignMessage(walletName, password, addr, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignMessage", reflect.TypeOf((*MockIManager)(nil).SignMessage), walletName, password, addr, msg)
}

// SignRawTransaction mocks base method.
func (m *MockIManager) SignRawTransaction(walletName, password string, rawTx []byte) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignRawTransaction", walletName, password, rawTx)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SignRawTransaction indicates an expected call of SignRawTransaction.
func (mr *MockIManagerMockRecorder) SignRawTransaction(walletName, password, rawTx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignRawTransaction", reflect.TypeOf((*MockIManager)(nil).SignRawTransaction), walletName, password, rawTx)
}

// SignTransaction mocks base method.
func (m *MockIManager) SignTransaction(walletName, password string, trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignTransaction", walletName, password, trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignTransaction indicates an expected call of SignTransaction.
func (mr *MockIManagerMockRecorder) SignTransaction(walletName, password, trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignTransaction", reflect.TypeOf((*MockIManager)(nil).SignTransaction), walletName, password, trx)
}

// Stake mocks base method.
func (m *MockIManager) Stake(walletName, addr string) (amount.Amount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stake", walletName, addr)
	ret0, _ := ret[0].(amount.Amount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stake indicates an expected call of Stake.
func (mr *MockIManagerMockRecorder) Stake(walletName, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stake", reflect.TypeOf((*MockIManager)(nil).Stake), walletName, addr)
}

// Start mocks base method.
func (m *MockIManager) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockIManagerMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockIManager)(nil).Start))
}

// Stop mocks base method.
func (m *MockIManager) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockIManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockIManager)(nil).Stop))
}

// TotalBalance mocks base method.
func (m *MockIManager) TotalBalance(walletName string) (amount.Amount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalBalance", walletName)
	ret0, _ := ret[0].(amount.Amount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalBalance indicates an expected call of TotalBalance.
func (mr *MockIManagerMockRecorder) TotalBalance(walletName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalBalance", reflect.TypeOf((*MockIManager)(nil).TotalBalance), walletName)
}

// TotalStake mocks base method.
func (m *MockIManager) TotalStake(walletName string) (amount.Amount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TotalStake", walletName)
	ret0, _ := ret[0].(amount.Amount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TotalStake indicates an expected call of TotalStake.
func (mr *MockIManagerMockRecorder) TotalStake(walletName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TotalStake", reflect.TypeOf((*MockIManager)(nil).TotalStake), walletName)
}

// UnloadWallet mocks base method.
func (m *MockIManager) UnloadWallet(walletName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnloadWallet", walletName)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnloadWallet indicates an expected call of UnloadWallet.
func (mr *MockIManagerMockRecorder) UnloadWallet(walletName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnloadWallet", reflect.TypeOf((*MockIManager)(nil).UnloadWallet), walletName)
}

// UpdatePassword mocks base method.
func (m *MockIManager) UpdatePassword(walletName, oldPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", walletName, oldPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockIManagerMockRecorder) UpdatePassword(walletName, oldPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockIManager)(nil).UpdatePassword), walletName, oldPassword, newPassword)
}

// WalletInfo mocks base method.
func (m *MockIManager) WalletInfo(walletName string) (*types.WalletInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletInfo", walletName)
	ret0, _ := ret[0].(*types.WalletInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WalletInfo indicates an expected call of WalletInfo.
func (mr *MockIManagerMockRecorder) WalletInfo(walletName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletInfo", reflect.TypeOf((*MockIManager)(nil).WalletInfo), walletName)
}
