linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - errchkjson
    - errname
    - errorlint
    - execinquery
    - exhaustive
    - exportloopref
    - forbidigo
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - lll
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagalign
    - tagliatelle
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    # - wrapcheck
    - zerologlint
    - nonamedreturns

linters-settings:
  gosimple:
    checks: ["all"]

  govet:
    enable-all: true
    disable: fieldalignment
    shadow:
        strict: true

  predeclared:
    # Comma-separated list of predeclared identifiers to not report on.
    # Default: ""
    ignore: "len"
    # Include method names and field names (i.e., qualified names) in checks.
    # Default: false
    q: true

  tagliatelle:
    # Check the struct tag name case.
    case:
      use-field-name: false
      rules:
        json: snake
        yaml: snake

  nonamedreturns:
    # Report named error if it is assigned inside defer.
    # Default: false
     report-error-in-defer: false

  gocritic:
    disabled-checks:
      - ifElseChain
      - unnamedResult
    enabled-tags:
      - diagnostic
      - style
      - performance

  nestif:
    # Minimal complexity of if statements to report.
    # Default: 5
    min-complexity: 6

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - maintidx
        - nestif
        - gocognit
        - forbidigo

    - linters:
        - govet
      text: "shadow: declaration of \"err\" shadows"
