project_name: zarb

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/zarb/
    env:
      - CGO_ENABLED=1

    # Omit the symbol table and debug information.
    # For more info refer to: https://golang.org/cmd/link/
    ldflags:
      - -s -w

    # GOOS list to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are darwin and linux.
    goos:
      - "${GOHOSTOS}"

    # GOARCH to build for.
    # For more info refer to: https://golang.org/doc/install/source#environment
    # Defaults are 386, amd64 and arm64.
    goarch:
      - amd64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums-${GOHOSTOS}.txt'
