// Code generated by MockGen. DO NOT EDIT.
// Source: txpool/interface.go
//
// Generated by this command:
//
//	mockgen -source=txpool/interface.go -destination=txpool/txpool_mock.go -package=txpool
//

// Package txpool is a generated GoMock package.
package txpool

import (
	reflect "reflect"

	sandbox "github.com/pactus-project/pactus/sandbox"
	amount "github.com/pactus-project/pactus/types/amount"
	block "github.com/pactus-project/pactus/types/block"
	tx "github.com/pactus-project/pactus/types/tx"
	payload "github.com/pactus-project/pactus/types/tx/payload"
	"go.uber.org/mock/gomock"
)

// MockTxPoolReader is a mock of TxPoolReader interface.
type MockTxPoolReader struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolReaderMockRecorder
	isgomock struct{}
}

// MockTxPoolReaderMockRecorder is the mock recorder for MockTxPoolReader.
type MockTxPoolReaderMockRecorder struct {
	mock *MockTxPoolReader
}

// NewMockTxPoolReader creates a new mock instance.
func NewMockTxPoolReader(ctrl *gomock.Controller) *MockTxPoolReader {
	mock := &MockTxPoolReader{ctrl: ctrl}
	mock.recorder = &MockTxPoolReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPoolReader) EXPECT() *MockTxPoolReaderMockRecorder {
	return m.recorder
}

// AllPendingTxs mocks base method.
func (m *MockTxPoolReader) AllPendingTxs() []*tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllPendingTxs")
	ret0, _ := ret[0].([]*tx.Tx)
	return ret0
}

// AllPendingTxs indicates an expected call of AllPendingTxs.
func (mr *MockTxPoolReaderMockRecorder) AllPendingTxs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllPendingTxs", reflect.TypeOf((*MockTxPoolReader)(nil).AllPendingTxs))
}

// EstimatedFee mocks base method.
func (m *MockTxPoolReader) EstimatedFee(amt amount.Amount, payloadType payload.Type) amount.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedFee", amt, payloadType)
	ret0, _ := ret[0].(amount.Amount)
	return ret0
}

// EstimatedFee indicates an expected call of EstimatedFee.
func (mr *MockTxPoolReaderMockRecorder) EstimatedFee(amt, payloadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedFee", reflect.TypeOf((*MockTxPoolReader)(nil).EstimatedFee), amt, payloadType)
}

// HasTx mocks base method.
func (m *MockTxPoolReader) HasTx(txID tx.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTx", txID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTx indicates an expected call of HasTx.
func (mr *MockTxPoolReaderMockRecorder) HasTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTx", reflect.TypeOf((*MockTxPoolReader)(nil).HasTx), txID)
}

// PendingTx mocks base method.
func (m *MockTxPoolReader) PendingTx(txID tx.ID) *tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingTx", txID)
	ret0, _ := ret[0].(*tx.Tx)
	return ret0
}

// PendingTx indicates an expected call of PendingTx.
func (mr *MockTxPoolReaderMockRecorder) PendingTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingTx", reflect.TypeOf((*MockTxPoolReader)(nil).PendingTx), txID)
}

// PrepareBlockTransactions mocks base method.
func (m *MockTxPoolReader) PrepareBlockTransactions() block.Txs {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareBlockTransactions")
	ret0, _ := ret[0].(block.Txs)
	return ret0
}

// PrepareBlockTransactions indicates an expected call of PrepareBlockTransactions.
func (mr *MockTxPoolReaderMockRecorder) PrepareBlockTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareBlockTransactions", reflect.TypeOf((*MockTxPoolReader)(nil).PrepareBlockTransactions))
}

// Size mocks base method.
func (m *MockTxPoolReader) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockTxPoolReaderMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockTxPoolReader)(nil).Size))
}

// MockTxPool is a mock of TxPool interface.
type MockTxPool struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolMockRecorder
	isgomock struct{}
}

// MockTxPoolMockRecorder is the mock recorder for MockTxPool.
type MockTxPoolMockRecorder struct {
	mock *MockTxPool
}

// NewMockTxPool creates a new mock instance.
func NewMockTxPool(ctrl *gomock.Controller) *MockTxPool {
	mock := &MockTxPool{ctrl: ctrl}
	mock.recorder = &MockTxPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPool) EXPECT() *MockTxPoolMockRecorder {
	return m.recorder
}

// AllPendingTxs mocks base method.
func (m *MockTxPool) AllPendingTxs() []*tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllPendingTxs")
	ret0, _ := ret[0].([]*tx.Tx)
	return ret0
}

// AllPendingTxs indicates an expected call of AllPendingTxs.
func (mr *MockTxPoolMockRecorder) AllPendingTxs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllPendingTxs", reflect.TypeOf((*MockTxPool)(nil).AllPendingTxs))
}

// AppendTx mocks base method.
func (m *MockTxPool) AppendTx(trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendTx", trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendTx indicates an expected call of AppendTx.
func (mr *MockTxPoolMockRecorder) AppendTx(trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendTx", reflect.TypeOf((*MockTxPool)(nil).AppendTx), trx)
}

// AppendTxAndBroadcast mocks base method.
func (m *MockTxPool) AppendTxAndBroadcast(trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppendTxAndBroadcast", trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendTxAndBroadcast indicates an expected call of AppendTxAndBroadcast.
func (mr *MockTxPoolMockRecorder) AppendTxAndBroadcast(trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendTxAndBroadcast", reflect.TypeOf((*MockTxPool)(nil).AppendTxAndBroadcast), trx)
}

// EstimatedFee mocks base method.
func (m *MockTxPool) EstimatedFee(amt amount.Amount, payloadType payload.Type) amount.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EstimatedFee", amt, payloadType)
	ret0, _ := ret[0].(amount.Amount)
	return ret0
}

// EstimatedFee indicates an expected call of EstimatedFee.
func (mr *MockTxPoolMockRecorder) EstimatedFee(amt, payloadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EstimatedFee", reflect.TypeOf((*MockTxPool)(nil).EstimatedFee), amt, payloadType)
}

// HandleCommittedBlock mocks base method.
func (m *MockTxPool) HandleCommittedBlock(blk *block.Block) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleCommittedBlock", blk)
}

// HandleCommittedBlock indicates an expected call of HandleCommittedBlock.
func (mr *MockTxPoolMockRecorder) HandleCommittedBlock(blk any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleCommittedBlock", reflect.TypeOf((*MockTxPool)(nil).HandleCommittedBlock), blk)
}

// HasTx mocks base method.
func (m *MockTxPool) HasTx(txID tx.ID) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTx", txID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTx indicates an expected call of HasTx.
func (mr *MockTxPoolMockRecorder) HasTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTx", reflect.TypeOf((*MockTxPool)(nil).HasTx), txID)
}

// PendingTx mocks base method.
func (m *MockTxPool) PendingTx(txID tx.ID) *tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingTx", txID)
	ret0, _ := ret[0].(*tx.Tx)
	return ret0
}

// PendingTx indicates an expected call of PendingTx.
func (mr *MockTxPoolMockRecorder) PendingTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingTx", reflect.TypeOf((*MockTxPool)(nil).PendingTx), txID)
}

// PrepareBlockTransactions mocks base method.
func (m *MockTxPool) PrepareBlockTransactions() block.Txs {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareBlockTransactions")
	ret0, _ := ret[0].(block.Txs)
	return ret0
}

// PrepareBlockTransactions indicates an expected call of PrepareBlockTransactions.
func (mr *MockTxPoolMockRecorder) PrepareBlockTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareBlockTransactions", reflect.TypeOf((*MockTxPool)(nil).PrepareBlockTransactions))
}

// SetNewSandboxAndRecheck mocks base method.
func (m *MockTxPool) SetNewSandboxAndRecheck(sbx sandbox.Sandbox) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetNewSandboxAndRecheck", sbx)
}

// SetNewSandboxAndRecheck indicates an expected call of SetNewSandboxAndRecheck.
func (mr *MockTxPoolMockRecorder) SetNewSandboxAndRecheck(sbx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetNewSandboxAndRecheck", reflect.TypeOf((*MockTxPool)(nil).SetNewSandboxAndRecheck), sbx)
}

// Size mocks base method.
func (m *MockTxPool) Size() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Size")
	ret0, _ := ret[0].(int)
	return ret0
}

// Size indicates an expected call of Size.
func (mr *MockTxPoolMockRecorder) Size() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Size", reflect.TypeOf((*MockTxPool)(nil).Size))
}
