// Code generated by MockGen. DO NOT EDIT.
// Source: state/interface.go
//
// Generated by this command:
//
//	mockgen -source=state/interface.go -destination=state/state_mock.go -package=state
//

// Package state is a generated GoMock package.
package state

import (
	reflect "reflect"
	time "time"

	crypto "github.com/pactus-project/pactus/crypto"
	bls "github.com/pactus-project/pactus/crypto/bls"
	hash "github.com/pactus-project/pactus/crypto/hash"
	genesis "github.com/pactus-project/pactus/genesis"
	param "github.com/pactus-project/pactus/state/param"
	store "github.com/pactus-project/pactus/store"
	types "github.com/pactus-project/pactus/types"
	account "github.com/pactus-project/pactus/types/account"
	amount "github.com/pactus-project/pactus/types/amount"
	block "github.com/pactus-project/pactus/types/block"
	certificate "github.com/pactus-project/pactus/types/certificate"
	protocol "github.com/pactus-project/pactus/types/protocol"
	tx "github.com/pactus-project/pactus/types/tx"
	payload "github.com/pactus-project/pactus/types/tx/payload"
	validator "github.com/pactus-project/pactus/types/validator"
	vote "github.com/pactus-project/pactus/types/vote"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// AccountByAddress mocks base method.
func (m *MockState) AccountByAddress(addr crypto.Address) (*account.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccountByAddress", addr)
	ret0, _ := ret[0].(*account.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccountByAddress indicates an expected call of AccountByAddress.
func (mr *MockStateMockRecorder) AccountByAddress(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccountByAddress", reflect.TypeOf((*MockState)(nil).AccountByAddress), addr)
}

// AddPendingTx mocks base method.
func (m *MockState) AddPendingTx(trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPendingTx", trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPendingTx indicates an expected call of AddPendingTx.
func (mr *MockStateMockRecorder) AddPendingTx(trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPendingTx", reflect.TypeOf((*MockState)(nil).AddPendingTx), trx)
}

// AddPendingTxAndBroadcast mocks base method.
func (m *MockState) AddPendingTxAndBroadcast(trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPendingTxAndBroadcast", trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPendingTxAndBroadcast indicates an expected call of AddPendingTxAndBroadcast.
func (mr *MockStateMockRecorder) AddPendingTxAndBroadcast(trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPendingTxAndBroadcast", reflect.TypeOf((*MockState)(nil).AddPendingTxAndBroadcast), trx)
}

// AllPendingTxs mocks base method.
func (m *MockState) AllPendingTxs() []*tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllPendingTxs")
	ret0, _ := ret[0].([]*tx.Tx)
	return ret0
}

// AllPendingTxs indicates an expected call of AllPendingTxs.
func (mr *MockStateMockRecorder) AllPendingTxs() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllPendingTxs", reflect.TypeOf((*MockState)(nil).AllPendingTxs))
}

// AvailabilityScore mocks base method.
func (m *MockState) AvailabilityScore(valNum int32) float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AvailabilityScore", valNum)
	ret0, _ := ret[0].(float64)
	return ret0
}

// AvailabilityScore indicates an expected call of AvailabilityScore.
func (mr *MockStateMockRecorder) AvailabilityScore(valNum any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AvailabilityScore", reflect.TypeOf((*MockState)(nil).AvailabilityScore), valNum)
}

// BlockHash mocks base method.
func (m *MockState) BlockHash(height types.Height) hash.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockHash", height)
	ret0, _ := ret[0].(hash.Hash)
	return ret0
}

// BlockHash indicates an expected call of BlockHash.
func (mr *MockStateMockRecorder) BlockHash(height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockHash", reflect.TypeOf((*MockState)(nil).BlockHash), height)
}

// BlockHeight mocks base method.
func (m *MockState) BlockHeight(h hash.Hash) types.Height {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BlockHeight", h)
	ret0, _ := ret[0].(types.Height)
	return ret0
}

// BlockHeight indicates an expected call of BlockHeight.
func (mr *MockStateMockRecorder) BlockHeight(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BlockHeight", reflect.TypeOf((*MockState)(nil).BlockHeight), h)
}

// CalculateFee mocks base method.
func (m *MockState) CalculateFee(amt amount.Amount, payloadType payload.Type) amount.Amount {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateFee", amt, payloadType)
	ret0, _ := ret[0].(amount.Amount)
	return ret0
}

// CalculateFee indicates an expected call of CalculateFee.
func (mr *MockStateMockRecorder) CalculateFee(amt, payloadType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateFee", reflect.TypeOf((*MockState)(nil).CalculateFee), amt, payloadType)
}

// ChainInfo mocks base method.
func (m *MockState) ChainInfo() *ChainInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainInfo")
	ret0, _ := ret[0].(*ChainInfo)
	return ret0
}

// ChainInfo indicates an expected call of ChainInfo.
func (mr *MockStateMockRecorder) ChainInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainInfo", reflect.TypeOf((*MockState)(nil).ChainInfo))
}

// CheckTransaction mocks base method.
func (m *MockState) CheckTransaction(trx *tx.Tx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTransaction", trx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckTransaction indicates an expected call of CheckTransaction.
func (mr *MockStateMockRecorder) CheckTransaction(trx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTransaction", reflect.TypeOf((*MockState)(nil).CheckTransaction), trx)
}

// Close mocks base method.
func (m *MockState) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockStateMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockState)(nil).Close))
}

// CommitBlock mocks base method.
func (m *MockState) CommitBlock(blk *block.Block, cert *certificate.Certificate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitBlock", blk, cert)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitBlock indicates an expected call of CommitBlock.
func (mr *MockStateMockRecorder) CommitBlock(blk, cert any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitBlock", reflect.TypeOf((*MockState)(nil).CommitBlock), blk, cert)
}

// CommittedBlock mocks base method.
func (m *MockState) CommittedBlock(height types.Height) (*store.CommittedBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommittedBlock", height)
	ret0, _ := ret[0].(*store.CommittedBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommittedBlock indicates an expected call of CommittedBlock.
func (mr *MockStateMockRecorder) CommittedBlock(height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommittedBlock", reflect.TypeOf((*MockState)(nil).CommittedBlock), height)
}

// CommittedTx mocks base method.
func (m *MockState) CommittedTx(txID tx.ID) (*store.CommittedTx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommittedTx", txID)
	ret0, _ := ret[0].(*store.CommittedTx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CommittedTx indicates an expected call of CommittedTx.
func (mr *MockStateMockRecorder) CommittedTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommittedTx", reflect.TypeOf((*MockState)(nil).CommittedTx), txID)
}

// CommitteeInfo mocks base method.
func (m *MockState) CommitteeInfo() *CommitteeInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitteeInfo")
	ret0, _ := ret[0].(*CommitteeInfo)
	return ret0
}

// CommitteeInfo indicates an expected call of CommitteeInfo.
func (mr *MockStateMockRecorder) CommitteeInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitteeInfo", reflect.TypeOf((*MockState)(nil).CommitteeInfo))
}

// CommitteeValidators mocks base method.
func (m *MockState) CommitteeValidators() []*validator.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitteeValidators")
	ret0, _ := ret[0].([]*validator.Validator)
	return ret0
}

// CommitteeValidators indicates an expected call of CommitteeValidators.
func (mr *MockStateMockRecorder) CommitteeValidators() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitteeValidators", reflect.TypeOf((*MockState)(nil).CommitteeValidators))
}

// Genesis mocks base method.
func (m *MockState) Genesis() *genesis.Genesis {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Genesis")
	ret0, _ := ret[0].(*genesis.Genesis)
	return ret0
}

// Genesis indicates an expected call of Genesis.
func (mr *MockStateMockRecorder) Genesis() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Genesis", reflect.TypeOf((*MockState)(nil).Genesis))
}

// IsInCommittee mocks base method.
func (m *MockState) IsInCommittee(addr crypto.Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsInCommittee", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsInCommittee indicates an expected call of IsInCommittee.
func (mr *MockStateMockRecorder) IsInCommittee(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsInCommittee", reflect.TypeOf((*MockState)(nil).IsInCommittee), addr)
}

// IsProposer mocks base method.
func (m *MockState) IsProposer(addr crypto.Address, round types.Round) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProposer", addr, round)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProposer indicates an expected call of IsProposer.
func (mr *MockStateMockRecorder) IsProposer(addr, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProposer", reflect.TypeOf((*MockState)(nil).IsProposer), addr, round)
}

// LastBlockHash mocks base method.
func (m *MockState) LastBlockHash() hash.Hash {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBlockHash")
	ret0, _ := ret[0].(hash.Hash)
	return ret0
}

// LastBlockHash indicates an expected call of LastBlockHash.
func (mr *MockStateMockRecorder) LastBlockHash() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBlockHash", reflect.TypeOf((*MockState)(nil).LastBlockHash))
}

// LastBlockHeight mocks base method.
func (m *MockState) LastBlockHeight() types.Height {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBlockHeight")
	ret0, _ := ret[0].(types.Height)
	return ret0
}

// LastBlockHeight indicates an expected call of LastBlockHeight.
func (mr *MockStateMockRecorder) LastBlockHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBlockHeight", reflect.TypeOf((*MockState)(nil).LastBlockHeight))
}

// LastBlockTime mocks base method.
func (m *MockState) LastBlockTime() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastBlockTime")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastBlockTime indicates an expected call of LastBlockTime.
func (mr *MockStateMockRecorder) LastBlockTime() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastBlockTime", reflect.TypeOf((*MockState)(nil).LastBlockTime))
}

// LastCertificate mocks base method.
func (m *MockState) LastCertificate() *certificate.Certificate {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastCertificate")
	ret0, _ := ret[0].(*certificate.Certificate)
	return ret0
}

// LastCertificate indicates an expected call of LastCertificate.
func (mr *MockStateMockRecorder) LastCertificate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastCertificate", reflect.TypeOf((*MockState)(nil).LastCertificate))
}

// Params mocks base method.
func (m *MockState) Params() *param.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Params")
	ret0, _ := ret[0].(*param.Params)
	return ret0
}

// Params indicates an expected call of Params.
func (mr *MockStateMockRecorder) Params() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Params", reflect.TypeOf((*MockState)(nil).Params))
}

// PendingTx mocks base method.
func (m *MockState) PendingTx(txID tx.ID) *tx.Tx {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingTx", txID)
	ret0, _ := ret[0].(*tx.Tx)
	return ret0
}

// PendingTx indicates an expected call of PendingTx.
func (mr *MockStateMockRecorder) PendingTx(txID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingTx", reflect.TypeOf((*MockState)(nil).PendingTx), txID)
}

// ProposeBlock mocks base method.
func (m *MockState) ProposeBlock(valKey *bls.ValidatorKey, rewardAddr crypto.Address) (*block.Block, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProposeBlock", valKey, rewardAddr)
	ret0, _ := ret[0].(*block.Block)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProposeBlock indicates an expected call of ProposeBlock.
func (mr *MockStateMockRecorder) ProposeBlock(valKey, rewardAddr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProposeBlock", reflect.TypeOf((*MockState)(nil).ProposeBlock), valKey, rewardAddr)
}

// Proposer mocks base method.
func (m *MockState) Proposer(round types.Round) *validator.Validator {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposer", round)
	ret0, _ := ret[0].(*validator.Validator)
	return ret0
}

// Proposer indicates an expected call of Proposer.
func (mr *MockStateMockRecorder) Proposer(round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposer", reflect.TypeOf((*MockState)(nil).Proposer), round)
}

// PublicKey mocks base method.
func (m *MockState) PublicKey(addr crypto.Address) (crypto.PublicKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublicKey", addr)
	ret0, _ := ret[0].(crypto.PublicKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublicKey indicates an expected call of PublicKey.
func (mr *MockStateMockRecorder) PublicKey(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublicKey", reflect.TypeOf((*MockState)(nil).PublicKey), addr)
}

// UpdateLastCertificate mocks base method.
func (m *MockState) UpdateLastCertificate(v *vote.Vote) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLastCertificate", v)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLastCertificate indicates an expected call of UpdateLastCertificate.
func (mr *MockStateMockRecorder) UpdateLastCertificate(v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLastCertificate", reflect.TypeOf((*MockState)(nil).UpdateLastCertificate), v)
}

// UpdateValidatorProtocolVersion mocks base method.
func (m *MockState) UpdateValidatorProtocolVersion(addr crypto.Address, ver protocol.Version) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateValidatorProtocolVersion", addr, ver)
}

// UpdateValidatorProtocolVersion indicates an expected call of UpdateValidatorProtocolVersion.
func (mr *MockStateMockRecorder) UpdateValidatorProtocolVersion(addr, ver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateValidatorProtocolVersion", reflect.TypeOf((*MockState)(nil).UpdateValidatorProtocolVersion), addr, ver)
}

// ValidateBlock mocks base method.
func (m *MockState) ValidateBlock(blk *block.Block, round types.Round) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateBlock", blk, round)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateBlock indicates an expected call of ValidateBlock.
func (mr *MockStateMockRecorder) ValidateBlock(blk, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateBlock", reflect.TypeOf((*MockState)(nil).ValidateBlock), blk, round)
}

// ValidatorAddresses mocks base method.
func (m *MockState) ValidatorAddresses() []crypto.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorAddresses")
	ret0, _ := ret[0].([]crypto.Address)
	return ret0
}

// ValidatorAddresses indicates an expected call of ValidatorAddresses.
func (mr *MockStateMockRecorder) ValidatorAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorAddresses", reflect.TypeOf((*MockState)(nil).ValidatorAddresses))
}

// ValidatorByAddress mocks base method.
func (m *MockState) ValidatorByAddress(addr crypto.Address) (*validator.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorByAddress", addr)
	ret0, _ := ret[0].(*validator.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatorByAddress indicates an expected call of ValidatorByAddress.
func (mr *MockStateMockRecorder) ValidatorByAddress(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorByAddress", reflect.TypeOf((*MockState)(nil).ValidatorByAddress), addr)
}

// ValidatorByNumber mocks base method.
func (m *MockState) ValidatorByNumber(number int32) (*validator.Validator, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidatorByNumber", number)
	ret0, _ := ret[0].(*validator.Validator)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidatorByNumber indicates an expected call of ValidatorByNumber.
func (mr *MockStateMockRecorder) ValidatorByNumber(number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidatorByNumber", reflect.TypeOf((*MockState)(nil).ValidatorByNumber), number)
}
