// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/manager/interface.go
//
// Generated by this command:
//
//	mockgen -source=consensus/manager/interface.go -destination=consensus/manager/manager_mock.go -package=manager
//

// Package manager is a generated GoMock package.
package manager

import (
	reflect "reflect"

	consensus "github.com/pactus-project/pactus/consensus"
	types "github.com/pactus-project/pactus/types"
	proposal "github.com/pactus-project/pactus/types/proposal"
	vote "github.com/pactus-project/pactus/types/vote"
	gomock "go.uber.org/mock/gomock"
)

// MockManagerReader is a mock of ManagerReader interface.
type MockManagerReader struct {
	ctrl     *gomock.Controller
	recorder *MockManagerReaderMockRecorder
	isgomock struct{}
}

// MockManagerReaderMockRecorder is the mock recorder for MockManagerReader.
type MockManagerReaderMockRecorder struct {
	mock *MockManagerReader
}

// NewMockManagerReader creates a new mock instance.
func NewMockManagerReader(ctrl *gomock.Controller) *MockManagerReader {
	mock := &MockManagerReader{ctrl: ctrl}
	mock.recorder = &MockManagerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManagerReader) EXPECT() *MockManagerReaderMockRecorder {
	return m.recorder
}

// HandleQueryProposal mocks base method.
func (m *MockManagerReader) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockManagerReaderMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockManagerReader)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockManagerReader) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockManagerReaderMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockManagerReader)(nil).HandleQueryVote), height, round)
}

// HasActiveInstance mocks base method.
func (m *MockManagerReader) HasActiveInstance() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveInstance")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveInstance indicates an expected call of HasActiveInstance.
func (mr *MockManagerReaderMockRecorder) HasActiveInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveInstance", reflect.TypeOf((*MockManagerReader)(nil).HasActiveInstance))
}

// HeightRound mocks base method.
func (m *MockManagerReader) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockManagerReaderMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockManagerReader)(nil).HeightRound))
}

// Instances mocks base method.
func (m *MockManagerReader) Instances() []consensus.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instances")
	ret0, _ := ret[0].([]consensus.Reader)
	return ret0
}

// Instances indicates an expected call of Instances.
func (mr *MockManagerReaderMockRecorder) Instances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instances", reflect.TypeOf((*MockManagerReader)(nil).Instances))
}

// Proposal mocks base method.
func (m *MockManagerReader) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockManagerReaderMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockManagerReader)(nil).Proposal))
}

// MockManager is a mock of Manager interface.
type MockManager struct {
	ctrl     *gomock.Controller
	recorder *MockManagerMockRecorder
	isgomock struct{}
}

// MockManagerMockRecorder is the mock recorder for MockManager.
type MockManagerMockRecorder struct {
	mock *MockManager
}

// NewMockManager creates a new mock instance.
func NewMockManager(ctrl *gomock.Controller) *MockManager {
	mock := &MockManager{ctrl: ctrl}
	mock.recorder = &MockManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManager) EXPECT() *MockManagerMockRecorder {
	return m.recorder
}

// AddVote mocks base method.
func (m *MockManager) AddVote(arg0 *vote.Vote) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddVote", arg0)
}

// AddVote indicates an expected call of AddVote.
func (mr *MockManagerMockRecorder) AddVote(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVote", reflect.TypeOf((*MockManager)(nil).AddVote), arg0)
}

// HandleQueryProposal mocks base method.
func (m *MockManager) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockManagerMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockManager)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockManager) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockManagerMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockManager)(nil).HandleQueryVote), height, round)
}

// HasActiveInstance mocks base method.
func (m *MockManager) HasActiveInstance() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveInstance")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveInstance indicates an expected call of HasActiveInstance.
func (mr *MockManagerMockRecorder) HasActiveInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveInstance", reflect.TypeOf((*MockManager)(nil).HasActiveInstance))
}

// HeightRound mocks base method.
func (m *MockManager) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockManagerMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockManager)(nil).HeightRound))
}

// Instances mocks base method.
func (m *MockManager) Instances() []consensus.Reader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instances")
	ret0, _ := ret[0].([]consensus.Reader)
	return ret0
}

// Instances indicates an expected call of Instances.
func (mr *MockManagerMockRecorder) Instances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instances", reflect.TypeOf((*MockManager)(nil).Instances))
}

// IsDeprecated mocks base method.
func (m *MockManager) IsDeprecated() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeprecated")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDeprecated indicates an expected call of IsDeprecated.
func (mr *MockManagerMockRecorder) IsDeprecated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeprecated", reflect.TypeOf((*MockManager)(nil).IsDeprecated))
}

// MoveToNewHeight mocks base method.
func (m *MockManager) MoveToNewHeight() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveToNewHeight")
}

// MoveToNewHeight indicates an expected call of MoveToNewHeight.
func (mr *MockManagerMockRecorder) MoveToNewHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToNewHeight", reflect.TypeOf((*MockManager)(nil).MoveToNewHeight))
}

// Proposal mocks base method.
func (m *MockManager) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockManagerMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockManager)(nil).Proposal))
}

// SetProposal mocks base method.
func (m *MockManager) SetProposal(prop *proposal.Proposal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProposal", prop)
}

// SetProposal indicates an expected call of SetProposal.
func (mr *MockManagerMockRecorder) SetProposal(prop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProposal", reflect.TypeOf((*MockManager)(nil).SetProposal), prop)
}
