// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/manager/interface.go
//
// Generated by this command:
//
//	mockgen -source=consensus/manager/interface.go -destination=consensus/manager/manager_mock.go -package=manager
//

// Package manager is a generated GoMock package.
package manager

import (
	reflect "reflect"

	consensus "github.com/pactus-project/pactus/consensus"
	types "github.com/pactus-project/pactus/types"
	proposal "github.com/pactus-project/pactus/types/proposal"
	vote "github.com/pactus-project/pactus/types/vote"
	gomock "go.uber.org/mock/gomock"
)

// MockConsensusManagerReader is a mock of ConsensusManagerReader interface.
type MockConsensusManagerReader struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusManagerReaderMockRecorder
	isgomock struct{}
}

// MockConsensusManagerReaderMockRecorder is the mock recorder for MockConsensusManagerReader.
type MockConsensusManagerReaderMockRecorder struct {
	mock *MockConsensusManagerReader
}

// NewMockConsensusManagerReader creates a new mock instance.
func NewMockConsensusManagerReader(ctrl *gomock.Controller) *MockConsensusManagerReader {
	mock := &MockConsensusManagerReader{ctrl: ctrl}
	mock.recorder = &MockConsensusManagerReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensusManagerReader) EXPECT() *MockConsensusManagerReaderMockRecorder {
	return m.recorder
}

// HandleQueryProposal mocks base method.
func (m *MockConsensusManagerReader) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockConsensusManagerReaderMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockConsensusManagerReader)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockConsensusManagerReader) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockConsensusManagerReaderMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockConsensusManagerReader)(nil).HandleQueryVote), height, round)
}

// HasActiveInstance mocks base method.
func (m *MockConsensusManagerReader) HasActiveInstance() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveInstance")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveInstance indicates an expected call of HasActiveInstance.
func (mr *MockConsensusManagerReaderMockRecorder) HasActiveInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveInstance", reflect.TypeOf((*MockConsensusManagerReader)(nil).HasActiveInstance))
}

// HeightRound mocks base method.
func (m *MockConsensusManagerReader) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockConsensusManagerReaderMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockConsensusManagerReader)(nil).HeightRound))
}

// Instances mocks base method.
func (m *MockConsensusManagerReader) Instances() []consensus.ConsensusReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instances")
	ret0, _ := ret[0].([]consensus.ConsensusReader)
	return ret0
}

// Instances indicates an expected call of Instances.
func (mr *MockConsensusManagerReaderMockRecorder) Instances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instances", reflect.TypeOf((*MockConsensusManagerReader)(nil).Instances))
}

// Proposal mocks base method.
func (m *MockConsensusManagerReader) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockConsensusManagerReaderMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockConsensusManagerReader)(nil).Proposal))
}

// MockConsensusManager is a mock of ConsensusManager interface.
type MockConsensusManager struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusManagerMockRecorder
	isgomock struct{}
}

// MockConsensusManagerMockRecorder is the mock recorder for MockConsensusManager.
type MockConsensusManagerMockRecorder struct {
	mock *MockConsensusManager
}

// NewMockConsensusManager creates a new mock instance.
func NewMockConsensusManager(ctrl *gomock.Controller) *MockConsensusManager {
	mock := &MockConsensusManager{ctrl: ctrl}
	mock.recorder = &MockConsensusManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensusManager) EXPECT() *MockConsensusManagerMockRecorder {
	return m.recorder
}

// AddVote mocks base method.
func (m *MockConsensusManager) AddVote(arg0 *vote.Vote) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddVote", arg0)
}

// AddVote indicates an expected call of AddVote.
func (mr *MockConsensusManagerMockRecorder) AddVote(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVote", reflect.TypeOf((*MockConsensusManager)(nil).AddVote), arg0)
}

// HandleQueryProposal mocks base method.
func (m *MockConsensusManager) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockConsensusManagerMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockConsensusManager)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockConsensusManager) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockConsensusManagerMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockConsensusManager)(nil).HandleQueryVote), height, round)
}

// HasActiveInstance mocks base method.
func (m *MockConsensusManager) HasActiveInstance() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasActiveInstance")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasActiveInstance indicates an expected call of HasActiveInstance.
func (mr *MockConsensusManagerMockRecorder) HasActiveInstance() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasActiveInstance", reflect.TypeOf((*MockConsensusManager)(nil).HasActiveInstance))
}

// HeightRound mocks base method.
func (m *MockConsensusManager) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockConsensusManagerMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockConsensusManager)(nil).HeightRound))
}

// Instances mocks base method.
func (m *MockConsensusManager) Instances() []consensus.ConsensusReader {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Instances")
	ret0, _ := ret[0].([]consensus.ConsensusReader)
	return ret0
}

// Instances indicates an expected call of Instances.
func (mr *MockConsensusManagerMockRecorder) Instances() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Instances", reflect.TypeOf((*MockConsensusManager)(nil).Instances))
}

// IsDeprecated mocks base method.
func (m *MockConsensusManager) IsDeprecated() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeprecated")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDeprecated indicates an expected call of IsDeprecated.
func (mr *MockConsensusManagerMockRecorder) IsDeprecated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeprecated", reflect.TypeOf((*MockConsensusManager)(nil).IsDeprecated))
}

// MoveToNewHeight mocks base method.
func (m *MockConsensusManager) MoveToNewHeight() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveToNewHeight")
}

// MoveToNewHeight indicates an expected call of MoveToNewHeight.
func (mr *MockConsensusManagerMockRecorder) MoveToNewHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToNewHeight", reflect.TypeOf((*MockConsensusManager)(nil).MoveToNewHeight))
}

// Proposal mocks base method.
func (m *MockConsensusManager) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockConsensusManagerMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockConsensusManager)(nil).Proposal))
}

// SetProposal mocks base method.
func (m *MockConsensusManager) SetProposal(prop *proposal.Proposal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProposal", prop)
}

// SetProposal indicates an expected call of SetProposal.
func (mr *MockConsensusManagerMockRecorder) SetProposal(prop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProposal", reflect.TypeOf((*MockConsensusManager)(nil).SetProposal), prop)
}
