// Code generated by MockGen. DO NOT EDIT.
// Source: execution/executor/interface.go
//
// Generated by this command:
//
//	mockgen -source=execution/executor/interface.go -destination=execution/executor/executor_mock.go -package=executor
//

// Package executor is a generated GoMock package.
package executor

import (
	reflect "reflect"

	sandbox "github.com/pactus-project/pactus/sandbox"
	gomock "go.uber.org/mock/gomock"
)

// MockExecutor is a mock of Executor interface.
type MockExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockExecutorMockRecorder
	isgomock struct{}
}

// MockExecutorMockRecorder is the mock recorder for MockExecutor.
type MockExecutorMockRecorder struct {
	mock *MockExecutor
}

// NewMockExecutor creates a new mock instance.
func NewMockExecutor(ctrl *gomock.Controller) *MockExecutor {
	mock := &MockExecutor{ctrl: ctrl}
	mock.recorder = &MockExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockExecutor) EXPECT() *MockExecutorMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockExecutor) Check(sbx sandbox.SandboxReader, strict bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", sbx, strict)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockExecutorMockRecorder) Check(sbx, strict any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockExecutor)(nil).Check), sbx, strict)
}

// Execute mocks base method.
func (m *MockExecutor) Execute(sbx sandbox.Sandbox) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Execute", sbx)
}

// Execute indicates an expected call of Execute.
func (mr *MockExecutorMockRecorder) Execute(sbx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockExecutor)(nil).Execute), sbx)
}
