// Code generated by MockGen. DO NOT EDIT.
// Source: consensus/interface.go
//
// Generated by this command:
//
//	mockgen -source=consensus/interface.go -destination=consensus/consensus_mock.go -package=consensus
//

// Package consensus is a generated GoMock package.
package consensus

import (
	reflect "reflect"

	bls "github.com/pactus-project/pactus/crypto/bls"
	hash "github.com/pactus-project/pactus/crypto/hash"
	types "github.com/pactus-project/pactus/types"
	proposal "github.com/pactus-project/pactus/types/proposal"
	vote "github.com/pactus-project/pactus/types/vote"
	gomock "go.uber.org/mock/gomock"
)

// MockReader is a mock of Reader interface.
type MockReader struct {
	ctrl     *gomock.Controller
	recorder *MockReaderMockRecorder
	isgomock struct{}
}

// MockReaderMockRecorder is the mock recorder for MockReader.
type MockReaderMockRecorder struct {
	mock *MockReader
}

// NewMockReader creates a new mock instance.
func NewMockReader(ctrl *gomock.Controller) *MockReader {
	mock := &MockReader{ctrl: ctrl}
	mock.recorder = &MockReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReader) EXPECT() *MockReaderMockRecorder {
	return m.recorder
}

// AllVotes mocks base method.
func (m *MockReader) AllVotes() []*vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllVotes")
	ret0, _ := ret[0].([]*vote.Vote)
	return ret0
}

// AllVotes indicates an expected call of AllVotes.
func (mr *MockReaderMockRecorder) AllVotes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllVotes", reflect.TypeOf((*MockReader)(nil).AllVotes))
}

// ConsensusKey mocks base method.
func (m *MockReader) ConsensusKey() *bls.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsensusKey")
	ret0, _ := ret[0].(*bls.PublicKey)
	return ret0
}

// ConsensusKey indicates an expected call of ConsensusKey.
func (mr *MockReaderMockRecorder) ConsensusKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsensusKey", reflect.TypeOf((*MockReader)(nil).ConsensusKey))
}

// HandleQueryProposal mocks base method.
func (m *MockReader) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockReaderMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockReader)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockReader) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockReaderMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockReader)(nil).HandleQueryVote), height, round)
}

// HasVote mocks base method.
func (m *MockReader) HasVote(h hash.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasVote", h)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasVote indicates an expected call of HasVote.
func (mr *MockReaderMockRecorder) HasVote(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVote", reflect.TypeOf((*MockReader)(nil).HasVote), h)
}

// HeightRound mocks base method.
func (m *MockReader) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockReaderMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockReader)(nil).HeightRound))
}

// IsActive mocks base method.
func (m *MockReader) IsActive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsActive indicates an expected call of IsActive.
func (mr *MockReaderMockRecorder) IsActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockReader)(nil).IsActive))
}

// IsProposer mocks base method.
func (m *MockReader) IsProposer() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProposer")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProposer indicates an expected call of IsProposer.
func (mr *MockReaderMockRecorder) IsProposer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProposer", reflect.TypeOf((*MockReader)(nil).IsProposer))
}

// Proposal mocks base method.
func (m *MockReader) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockReaderMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockReader)(nil).Proposal))
}

// MockConsensus is a mock of Consensus interface.
type MockConsensus struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusMockRecorder
	isgomock struct{}
}

// MockConsensusMockRecorder is the mock recorder for MockConsensus.
type MockConsensusMockRecorder struct {
	mock *MockConsensus
}

// NewMockConsensus creates a new mock instance.
func NewMockConsensus(ctrl *gomock.Controller) *MockConsensus {
	mock := &MockConsensus{ctrl: ctrl}
	mock.recorder = &MockConsensusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensus) EXPECT() *MockConsensusMockRecorder {
	return m.recorder
}

// AddVote mocks base method.
func (m *MockConsensus) AddVote(arg0 *vote.Vote) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddVote", arg0)
}

// AddVote indicates an expected call of AddVote.
func (mr *MockConsensusMockRecorder) AddVote(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddVote", reflect.TypeOf((*MockConsensus)(nil).AddVote), arg0)
}

// AllVotes mocks base method.
func (m *MockConsensus) AllVotes() []*vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllVotes")
	ret0, _ := ret[0].([]*vote.Vote)
	return ret0
}

// AllVotes indicates an expected call of AllVotes.
func (mr *MockConsensusMockRecorder) AllVotes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllVotes", reflect.TypeOf((*MockConsensus)(nil).AllVotes))
}

// ConsensusKey mocks base method.
func (m *MockConsensus) ConsensusKey() *bls.PublicKey {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsensusKey")
	ret0, _ := ret[0].(*bls.PublicKey)
	return ret0
}

// ConsensusKey indicates an expected call of ConsensusKey.
func (mr *MockConsensusMockRecorder) ConsensusKey() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsensusKey", reflect.TypeOf((*MockConsensus)(nil).ConsensusKey))
}

// HandleQueryProposal mocks base method.
func (m *MockConsensus) HandleQueryProposal(height types.Height, round types.Round) *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryProposal", height, round)
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// HandleQueryProposal indicates an expected call of HandleQueryProposal.
func (mr *MockConsensusMockRecorder) HandleQueryProposal(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryProposal", reflect.TypeOf((*MockConsensus)(nil).HandleQueryProposal), height, round)
}

// HandleQueryVote mocks base method.
func (m *MockConsensus) HandleQueryVote(height types.Height, round types.Round) *vote.Vote {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleQueryVote", height, round)
	ret0, _ := ret[0].(*vote.Vote)
	return ret0
}

// HandleQueryVote indicates an expected call of HandleQueryVote.
func (mr *MockConsensusMockRecorder) HandleQueryVote(height, round any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleQueryVote", reflect.TypeOf((*MockConsensus)(nil).HandleQueryVote), height, round)
}

// HasVote mocks base method.
func (m *MockConsensus) HasVote(h hash.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasVote", h)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasVote indicates an expected call of HasVote.
func (mr *MockConsensusMockRecorder) HasVote(h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasVote", reflect.TypeOf((*MockConsensus)(nil).HasVote), h)
}

// HeightRound mocks base method.
func (m *MockConsensus) HeightRound() (types.Height, types.Round) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeightRound")
	ret0, _ := ret[0].(types.Height)
	ret1, _ := ret[1].(types.Round)
	return ret0, ret1
}

// HeightRound indicates an expected call of HeightRound.
func (mr *MockConsensusMockRecorder) HeightRound() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeightRound", reflect.TypeOf((*MockConsensus)(nil).HeightRound))
}

// IsActive mocks base method.
func (m *MockConsensus) IsActive() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsActive")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsActive indicates an expected call of IsActive.
func (mr *MockConsensusMockRecorder) IsActive() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsActive", reflect.TypeOf((*MockConsensus)(nil).IsActive))
}

// IsDeprecated mocks base method.
func (m *MockConsensus) IsDeprecated() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDeprecated")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDeprecated indicates an expected call of IsDeprecated.
func (mr *MockConsensusMockRecorder) IsDeprecated() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDeprecated", reflect.TypeOf((*MockConsensus)(nil).IsDeprecated))
}

// IsProposer mocks base method.
func (m *MockConsensus) IsProposer() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsProposer")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsProposer indicates an expected call of IsProposer.
func (mr *MockConsensusMockRecorder) IsProposer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsProposer", reflect.TypeOf((*MockConsensus)(nil).IsProposer))
}

// MoveToNewHeight mocks base method.
func (m *MockConsensus) MoveToNewHeight() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MoveToNewHeight")
}

// MoveToNewHeight indicates an expected call of MoveToNewHeight.
func (mr *MockConsensusMockRecorder) MoveToNewHeight() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MoveToNewHeight", reflect.TypeOf((*MockConsensus)(nil).MoveToNewHeight))
}

// Proposal mocks base method.
func (m *MockConsensus) Proposal() *proposal.Proposal {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Proposal")
	ret0, _ := ret[0].(*proposal.Proposal)
	return ret0
}

// Proposal indicates an expected call of Proposal.
func (mr *MockConsensusMockRecorder) Proposal() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Proposal", reflect.TypeOf((*MockConsensus)(nil).Proposal))
}

// SetProposal mocks base method.
func (m *MockConsensus) SetProposal(prop *proposal.Proposal) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetProposal", prop)
}

// SetProposal indicates an expected call of SetProposal.
func (mr *MockConsensusMockRecorder) SetProposal(prop any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetProposal", reflect.TypeOf((*MockConsensus)(nil).SetProposal), prop)
}
