// Code generated by MockGen. DO NOT EDIT.
// Source: wallet/storage/interface.go
//
// Generated by this command:
//
//	mockgen -source=wallet/storage/interface.go -destination=wallet/storage/storage_mock.go -package=storage
//

// Package storage is a generated GoMock package.
package storage

import (
	reflect "reflect"

	amount "github.com/pactus-project/pactus/types/amount"
	types "github.com/pactus-project/pactus/wallet/types"
	vault "github.com/pactus-project/pactus/wallet/vault"
	gomock "go.uber.org/mock/gomock"
)

// MockIStorage is a mock of IStorage interface.
type MockIStorage struct {
	ctrl     *gomock.Controller
	recorder *MockIStorageMockRecorder
	isgomock struct{}
}

// MockIStorageMockRecorder is the mock recorder for MockIStorage.
type MockIStorageMockRecorder struct {
	mock *MockIStorage
}

// NewMockIStorage creates a new mock instance.
func NewMockIStorage(ctrl *gomock.Controller) *MockIStorage {
	mock := &MockIStorage{ctrl: ctrl}
	mock.recorder = &MockIStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIStorage) EXPECT() *MockIStorageMockRecorder {
	return m.recorder
}

// AddressCount mocks base method.
func (m *MockIStorage) AddressCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// AddressCount indicates an expected call of AddressCount.
func (mr *MockIStorageMockRecorder) AddressCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressCount", reflect.TypeOf((*MockIStorage)(nil).AddressCount))
}

// AddressInfo mocks base method.
func (m *MockIStorage) AddressInfo(address string) (*types.AddressInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddressInfo", address)
	ret0, _ := ret[0].(*types.AddressInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddressInfo indicates an expected call of AddressInfo.
func (mr *MockIStorageMockRecorder) AddressInfo(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddressInfo", reflect.TypeOf((*MockIStorage)(nil).AddressInfo), address)
}

// AllAddresses mocks base method.
func (m *MockIStorage) AllAddresses() []types.AddressInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AllAddresses")
	ret0, _ := ret[0].([]types.AddressInfo)
	return ret0
}

// AllAddresses indicates an expected call of AllAddresses.
func (mr *MockIStorageMockRecorder) AllAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AllAddresses", reflect.TypeOf((*MockIStorage)(nil).AllAddresses))
}

// Clone mocks base method.
func (m *MockIStorage) Clone(path string) (IStorage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clone", path)
	ret0, _ := ret[0].(IStorage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clone indicates an expected call of Clone.
func (mr *MockIStorageMockRecorder) Clone(path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockIStorage)(nil).Clone), path)
}

// Close mocks base method.
func (m *MockIStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIStorage)(nil).Close))
}

// GetPendingTransactions mocks base method.
func (m *MockIStorage) GetPendingTransactions() (map[string]*types.TransactionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTransactions")
	ret0, _ := ret[0].(map[string]*types.TransactionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTransactions indicates an expected call of GetPendingTransactions.
func (mr *MockIStorageMockRecorder) GetPendingTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTransactions", reflect.TypeOf((*MockIStorage)(nil).GetPendingTransactions))
}

// GetTransaction mocks base method.
func (m *MockIStorage) GetTransaction(id string) (*types.TransactionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransaction", id)
	ret0, _ := ret[0].(*types.TransactionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransaction indicates an expected call of GetTransaction.
func (mr *MockIStorageMockRecorder) GetTransaction(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransaction", reflect.TypeOf((*MockIStorage)(nil).GetTransaction), id)
}

// HasAddress mocks base method.
func (m *MockIStorage) HasAddress(address string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasAddress", address)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasAddress indicates an expected call of HasAddress.
func (mr *MockIStorageMockRecorder) HasAddress(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasAddress", reflect.TypeOf((*MockIStorage)(nil).HasAddress), address)
}

// HasTransaction mocks base method.
func (m *MockIStorage) HasTransaction(id string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasTransaction", id)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasTransaction indicates an expected call of HasTransaction.
func (mr *MockIStorageMockRecorder) HasTransaction(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasTransaction", reflect.TypeOf((*MockIStorage)(nil).HasTransaction), id)
}

// InsertAddress mocks base method.
func (m *MockIStorage) InsertAddress(info *types.AddressInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertAddress", info)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertAddress indicates an expected call of InsertAddress.
func (mr *MockIStorageMockRecorder) InsertAddress(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertAddress", reflect.TypeOf((*MockIStorage)(nil).InsertAddress), info)
}

// InsertTransaction mocks base method.
func (m *MockIStorage) InsertTransaction(info *types.TransactionInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertTransaction", info)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertTransaction indicates an expected call of InsertTransaction.
func (mr *MockIStorageMockRecorder) InsertTransaction(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertTransaction", reflect.TypeOf((*MockIStorage)(nil).InsertTransaction), info)
}

// IsLegacy mocks base method.
func (m *MockIStorage) IsLegacy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLegacy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsLegacy indicates an expected call of IsLegacy.
func (mr *MockIStorageMockRecorder) IsLegacy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLegacy", reflect.TypeOf((*MockIStorage)(nil).IsLegacy))
}

// QueryTransactions mocks base method.
func (m *MockIStorage) QueryTransactions(params QueryParams) ([]*types.TransactionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "QueryTransactions", params)
	ret0, _ := ret[0].([]*types.TransactionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// QueryTransactions indicates an expected call of QueryTransactions.
func (mr *MockIStorageMockRecorder) QueryTransactions(params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueryTransactions", reflect.TypeOf((*MockIStorage)(nil).QueryTransactions), params)
}

// SetDefaultFee mocks base method.
func (m *MockIStorage) SetDefaultFee(fee amount.Amount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetDefaultFee", fee)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetDefaultFee indicates an expected call of SetDefaultFee.
func (mr *MockIStorageMockRecorder) SetDefaultFee(fee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefaultFee", reflect.TypeOf((*MockIStorage)(nil).SetDefaultFee), fee)
}

// UpdateAddress mocks base method.
func (m *MockIStorage) UpdateAddress(info *types.AddressInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAddress", info)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAddress indicates an expected call of UpdateAddress.
func (mr *MockIStorageMockRecorder) UpdateAddress(info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAddress", reflect.TypeOf((*MockIStorage)(nil).UpdateAddress), info)
}

// UpdateTransactionStatus mocks base method.
func (m *MockIStorage) UpdateTransactionStatus(id string, status types.TransactionStatus, blockHeight uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransactionStatus", id, status, blockHeight)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransactionStatus indicates an expected call of UpdateTransactionStatus.
func (mr *MockIStorageMockRecorder) UpdateTransactionStatus(id, status, blockHeight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransactionStatus", reflect.TypeOf((*MockIStorage)(nil).UpdateTransactionStatus), id, status, blockHeight)
}

// UpdateVault mocks base method.
func (m *MockIStorage) UpdateVault(arg0 *vault.Vault) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateVault", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateVault indicates an expected call of UpdateVault.
func (mr *MockIStorageMockRecorder) UpdateVault(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateVault", reflect.TypeOf((*MockIStorage)(nil).UpdateVault), arg0)
}

// Vault mocks base method.
func (m *MockIStorage) Vault() *vault.Vault {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Vault")
	ret0, _ := ret[0].(*vault.Vault)
	return ret0
}

// Vault indicates an expected call of Vault.
func (mr *MockIStorageMockRecorder) Vault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Vault", reflect.TypeOf((*MockIStorage)(nil).Vault))
}

// WalletInfo mocks base method.
func (m *MockIStorage) WalletInfo() *types.WalletInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WalletInfo")
	ret0, _ := ret[0].(*types.WalletInfo)
	return ret0
}

// WalletInfo indicates an expected call of WalletInfo.
func (mr *MockIStorageMockRecorder) WalletInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WalletInfo", reflect.TypeOf((*MockIStorage)(nil).WalletInfo))
}
