

on: [pull_request]
name: Build and test (mac-os)
jobs:
  unit-test:
    runs-on: macos-latest

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build
      run: make build

    # Only unit-tests for mac-OS,
    - name: Unit tests
      run: make unit_test

